services:
  minio:
    image: 'minio/minio:RELEASE.2023-06-09T07-32-12Z'
    environment:
      - 'MINIO_ACCESS_KEY=minio'
      - 'MINIO_SECRET_KEY=minio123'
    ports:
      - '9100:9000'
      - '9101:9001'
    command: >
      server /data --console-address ":9001"
  minio-createBucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 15;
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/s3sample-bucket;
      exit 0;
      "
