spring:
  datasource:
    url: jdbc:h2:./s3sample;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-main.yaml
application:
  object-storage:
    service-endpoint: http://localhost:9100
    bucket-name: s3sample-bucket
    access-key: minio
    secret-key: minio
